{% set name = "rethinkdb-python" %}
{% set version = "2.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/rethinkdb/rethinkdb-{{ version }}.tar.gz
  sha256: 55ecf7447dc11fec0e2ce9aac4ba4c0b57fdc5c9c57d77ee673d59d245c74666

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  noarch: python
  entry_points:
    - rethinkdb-import = rethinkdb._import:main
    - rethinkdb-dump = rethinkdb._dump:main
    - rethinkdb-export = rethinkdb._export:main
    - rethinkdb-restore = rethinkdb._restore:main
    - rethinkdb-index-rebuild = rethinkdb._index_rebuild:main
    - rethinkdb-repl = rethinkdb.__main__:startInterpreter

requirements:
  host:
    - looseversion
    - pip
    - python {{ python_min }}
    - setuptools
    - six
  run:
    - __unix # to skip win, as a noarch package
    - looseversion
    - python >={{ python_min }}
    - six
    - tornado
    - trio

test:
  imports:
    - rethinkdb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rethinkdb.com/api/python/
  summary: Python driver for RethinkDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
